on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/common/**'
      - 'packages/ui-tars/**'
      - '.github/workflows/e2e-ui-tars.yml'
      - 'apps/ui-tars/**'
  push:
    branches:
      - 'main'

name: UI-TARS E2E Test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true
env:
  CI: e2e
  NODE_OPTIONS: --max-old-space-size=8192
  HUSKY: 0
  UI_TARS_APP_PRIVATE_KEY_BASE64: e2e-ui-tars-test-private-key

permissions:
  id-token: write
  contents: read
  attestations: read

jobs:
  e2e:
    name: E2E
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Cache turbo
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306  # v5.0.3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install pnpm
        run: npm install -g pnpm@9
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # v6.2.0
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Python setuptools
        if: matrix.os == 'macos-latest'
        run: brew install python-setuptools
      - name: Install appdmg
        if: matrix.os == 'macos-latest'
        run: npm install -g appdmg
      - name: Install dependencies
        run: pnpm install
      - name: Run e2e
        run: npm exec turbo run ui-tars-desktop#test:e2e
